### ISSUE TITLE
Update the favicon and the header title.

### ISSUE THREAD

**Issue by nith1n** [nith1n/arrow-fashion#2]
The header tilte should be "Arrow Fashion Store"
The favicon should be :

![image](https://github.com/nith1n/arrow-fashion/assets/90139606/092b6471-92c1-4f8f-8a00-17e155cca85f)

**Comment by bharath090909** [comment]
@nith1n can i take on this issue ?

**Comment by bharath090909** [comment]
@nith1n I have completed the task and raised a PR. Look into it and let me know if any changes required.

**Comment by nith1n** [comment]
Thanks for the PR. ✨️
